name: Deploy Flask App to AWS

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3
      run: |
        echo "Step 1: Checking out code..."


    - name: set up python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Step 2: Set up AWS CLI
    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    # Step 3: Transfer code to EC2 instance
    - name: Transfer Code to EC2
      run: |
        echo "${{ secrets.EC2_KEY }}" > Arunachalam_Key_Value_Pair.pem  # Save the secret to a file
        chmod 600 Arunachalam_Key_Value_Pair.pem  # Restrict permissions for the key
        scp -o StrictHostKeyChecking=no -i ${{ secrets.EC2_KEY }} -r * ec2-user@${{ secrets.EC2_PUBLIC_IP }}:/home/ec2-user/flask-app

    # Step 4: Connect to EC2 and set up Flask app
    - name: Set Up Flask App on EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_KEY }} ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
        cd /home/ec2-user/flask-app
        python3 -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        nohup python app.py > flask.log 2>&1 &
        EOF
